Milestone 3 : Created final mobile
Theodoraldo/Portfolio-finish-mobile-version pull request #1
Opened 2023-03-24 17:02 UTC by Theodoraldo

## Portfolio : mobile version

-Add work section of built projects
-Add about me section

2023-03-24 17:32 UTC, Shisui6 requested changes
Hi @Theodoraldo, 

# Requires Changes 🍀
You have done a great job so far!
Your design is good 🖼️, and your code follows best practices. However, there are a few issues that you still need to work on🪲.

## Highlights
- Good design ✅
- Nice use of grid and flexbox ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

You can also consider the following:

N/A

Cheers and Happy coding!🍻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid, unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-24 17:32 UTC, Shisui6 commented on index.html
> +<!DOCTYPE html>
You've done well creating the works and about sections but please note that you are not supposed to create a new repository for every new milestone😅. You are supposed to use the same repository and create  new branches for each milestone to be merged into the main branch. This way, you build out your portfolio in one repository step by step. Please add your approved code for the toolbar and headline sections into this repository and so your portfolio will have all sections🙏.

2023-03-24 17:32 UTC, Shisui6 commented on index.html
> +    <div class="container">
Kindly wrap your works section in a `<section>` tag🙏. This is for semantic reasons, as section tags are used to identify different parts of a webpage

2023-03-24 17:32 UTC, Shisui6 commented on custom.css
> +}
Kindly update the works section to match the figma design better🙏

Your design:
<img width="213" alt="image" src="https://user-images.githubusercontent.com/37116322/227596252-377748b5-cd5e-40dd-b92b-3a4038efc98c.png">

Figma design:
<img width="192" alt="image" src="https://user-images.githubusercontent.com/37116322/227596326-13059daf-3912-49e5-a1cb-3ac38bac914a.png">

A few things to note:
- Please make the left and right margins of each card even
- Please update to background color of the section to match the template. I believe `#f7f7f9` should do it

2023-03-24 17:32 UTC, Shisui6 commented on index.html
> +      <h1 class="banner-title">About Myself</h1>
Kindly update this element to use another `<hx>` element apart from `<h1>`🙏. This is for semantic reasons, as a good webpage is typically supposed to have one `<h1>` tag which represents the main title

2023-03-24 17:32 UTC, Shisui6 commented on index.html
> +          <li>Languages</li>
Your about section is looking really good✨. But please add the arrow icons next to each technology category as shown in the figma design.

Your design:
<img width="198" alt="image" src="https://user-images.githubusercontent.com/37116322/227598022-65a88a65-bfd2-4016-9fd9-5f9aa0b02567.png">

Figma design:
<img width="222" alt="image" src="https://user-images.githubusercontent.com/37116322/227598098-9203731a-4da0-48f2-987a-f0e273435758.png">

2023-03-24 17:32 UTC, Shisui6 commented on custom.css
> +@import url("https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap");
Please remove all lines that start with `>` from your readme file🙏. These lines are comments meant to help you the project owner fill out each section properly and is not meant for your users to see. It makes your readme look unprofessional

2023-03-25 00:34 UTC, Shedrack-Sunday requested changes
Hi @Theodoraldo      👋 

# CHANGES REQUIRED ♻️

Great work on the project 👏
You've done well implementing the requirements,  However, there are a few you need to work on, to move to the next project. 💯

 
![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights:
✔️ README setup
✔️  Linters passed
  
# Required Changes ♻️

- [x] I must admit you have really put in the effort so far in this project, however, the changes needed has to do with semantics

_check the comment section for a detailed review_ 

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-03-25 00:34 UTC, Shedrack-Sunday commented on index.html
> +      <h1 class="banner-title">About Myself</h1>
- [ ] Kindly update this element to use another `hx` element apart from `h1`🙏. This is for semantic reasons, as a good webpage is typically supposed to have one h1 tag which represents the main title.
- This was highlighted by the previous reviewer, kindly make the change

2023-03-25 00:53 UTC, ouasamine approved these changes
Hi @Theodoraldo 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Nice work on the UI ✔️ 
- Good work on the project's documentation 👏🏽 👏🏽 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-25 01:00 UTC, merged