Portfolio : Hamburger menu
Theodoraldo/Portfolio-finish-mobile-version pull request #5
Opened 2023-04-11 08:14 UTC by Theodoraldo

# At this point, we:
- Added JavaScript linters to project
- Added mobile menu functionality

2023-04-11 14:44 UTC, Gambit142 reviewed
Hi @Theodoraldo @Bifabig 👋, 

While you made a great effort in this project, I cannot proceed to review your code.

## Invalid Code Review Request

- Kindly use the Eslint for this project. The Eslint ensures we write clean and readable JavaScript codes. Kindly setup Eslint for this project. 👍 😎 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-11 15:54 UTC, Omar-Muhamad reviewed
# Invalid ❌

Hi Team,

#### While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

#### Your Code Review Request is marked as invalid for this reason:

- [ ] Kindy add Eslint configuration by adding the correct `linters.yml` file according to [this link](https://github.com/microverseinc/linters-config/tree/master/html-css-js).

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

2023-04-11 18:00 UTC, huseyinbiyik commented
Hi team,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![Alt Text](https://media.giphy.com/media/xUPGcwE3CUkXlvonug/giphy.gif)

## Invalid Code Review Request

- Kindly use [Microverse Readme template](https://github.com/microverseinc/readme-template) and modify the file to match your project and remove sections that don't apply. Please remove all the instructions targeting you. For example: "Describe how a new developer could make use of your project." This is crucial to have a professional and instructive repository. 👌 
![9bb4540b9ee9939697a47ad7d2975ef9](https://user-images.githubusercontent.com/25887253/231249167-e8a542dc-35d4-4c77-b22f-85b3bb492805.png)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-11 18:37 UTC, Zuhaib042 requested changes
Hi @Theodoraldo  @huseyinbiyik 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://media.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif)

## Highlights
✅ Descriptive PR
✅ Correct Github flow

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-11 18:37 UTC, Zuhaib042 commented on custom.css
> +  }
- [ ] One of the requirements in this milestone is to follow Figma design in `(font, colors, images, text, margins).`. right now the nav-links in your design are not compatible with Figma design in font size, font-weight, and the margin between these navlinks. Kindly consider fixing these 3 things. you can take help from the inspect tab on figma website.
your design
![re](https://user-images.githubusercontent.com/96683843/231255986-402799a1-b3bd-4778-8da6-0ee7e6d4ea7c.jpg)

figma design
![qw](https://user-images.githubusercontent.com/96683843/231256011-2da203dc-3ecd-49a9-9c4a-8b371b695cec.jpg)

2023-04-11 18:37 UTC, Zuhaib042 commented on custom.css
> +  overflow-x: hidden;
- [ ] Right now this property is not working and the scroll behavior works even when you click on the hamburger menu. to get the desired results in this scenario, kindly consider changing this to `overflow-y: hidden`. I have checked it and it works perfectly with the given CSS styling.
your design

https://user-images.githubusercontent.com/96683843/231257723-9ef1d74b-caf3-475b-afed-454a73904723.mov

2023-04-11 18:45 UTC, Theodoraldo commented on custom.css
> +  overflow-x: hidden;
Thanks very much for your feedback. 👍👍👍👍👍 Will implement the right away........

2023-04-11 21:11 UTC, BenMukebo requested changes
### Hi Team,

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight 💪🏻

- Both [JavaScript](https://github.com/microverseinc/linters-config/tree/master/javascript) and [HTML&CSS](https://github.com/microverseinc/linters-config/tree/master/html-css) linters in the project repository have been set up correctly. ✔️  
-  When the user clicks the hamburger button, the mobile menu appears.✔️ 
- When the user clicks the close (X) button, the mobile menu disappears.✔️ 
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-11 21:11 UTC, BenMukebo commented on README.md
- [OPTIONAL]  Please, add a meaningful  `Project description`. Remember A project description is a high-level overview of why you're doing a project. The document explains a project's objectives and essential qualities. Is an essential document that provides your audience with a comprehensive overview of the project. 😉 💯 


 - [OPTIONAL ] Kindly, it would be nice to add explicit steps for cloning and running your app, as this will help you, non-technical users. You can put the steps to clone and run the project in a new Getting Started section under the project's description. This includes `git clone URL` , `cd..`, etc.

- The README file It is the first file a person will see when they encounter your project, so it should be fairly brief but detailed. It will make your project stand out from a bunch of others.

2023-04-11 21:11 UTC, BenMukebo commented on README.md
>  <!-- AUTHORS -->
- [OPTIONAL] Move `Biftu Girma`  info to the Authors section. the `Contributions`  is supposed to contain the link to the issues page. 👍🏻 

![11](https://user-images.githubusercontent.com/79058364/231284212-fa0a5efe-208b-4645-9aae-6a9c61d47f8a.png)

2023-04-11 21:11 UTC, BenMukebo commented on README.md
> +
- [OPTIONAL] As said above remove this from here, This should be in the `Authors` section

2023-04-11 21:11 UTC, BenMukebo commented on README.md
> +
- [OPTIONAL] KIndly Let's add the necessary information to the "Show your support" and "Acknowledgements" sections, ✍🏻  you need to keep your README file descriptive by completing all sections

![image](https://user-images.githubusercontent.com/79058364/231310169-85704c09-819b-4579-b21b-2a901e6daa58.png)

2023-04-11 21:11 UTC, BenMukebo commented on README.md
> +
- [OPTIONAL] I also recommend that you delete the Note: 👇🏻 in your License section as these are instructions on how to complete the License section.


![image](https://user-images.githubusercontent.com/79058364/220769702-9dbcadda-aa00-4d1c-990f-cf6ad4f5c6c9.png)

2023-04-11 21:11 UTC, BenMukebo commented on custom.css
>  }
- [ ] As requested by the previous reviewer, this property does not work as expected instead, it prevents your page from being scrollable, this would only be applied when you click on the hamburger menu to get the mobile menu page. please prevent the sub-background from scrolling only when the navigation bar is open, which will make your mobile menu match the original design.💯 🥇

- [ ]  The hamburger and closed button must follow the design from [the chosen template in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1) (e.g., font, colors, images, tests, margins). how about download the icon image from template Figma design to make sure you are using the same icon with the original design👍🏻 

![Screenshot from 2023-04-11 22-58-03](https://user-images.githubusercontent.com/79058364/231287784-7351d69c-eccf-4622-a463-46190317656f.png)


-  Adding these features will make your design look great and look exactly like the Figma design, I highly recommend you do this in the meantime, I'll approve this project since the previous reviewer is skipping this.

2023-04-11 21:11 UTC, BenMukebo commented on custom.css
> +  overflow: hidden;
- [ ] Great job so far! 👏🏻  however according to the project requirement, 🤔  on the desktop size,  the closed button, and the menu mobile page must not be visible. Kindly correct this. You can use your `@media screen and (min-width: 768px) {`  to display none of your navigation mobile menu. 😃 


![image](https://user-images.githubusercontent.com/79058364/231287993-d9449214-2041-4124-84a6-db5ef54b8d7e.png)

2023-04-12 13:24 UTC, joskalenda requested changes
| STATUS: REQUIRED CHANGES ♻️  |
|--------------------------------|
| Hi @Bifabig , |
|Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there! |
| <img src="https://media2.giphy.com/media/l1KVaj5UcbHwrBMqI/giphy.gif"/> |

## Highlights

- [ ].. ✅ Good commit messages
- [ ].. ✅ Green linters

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-12 13:24 UTC, joskalenda commented on custom.css
> +  overflow-x: hidden;
- [ ] As requested by previous reviewers, this overflow did not work as expected, it prevent your app from scrolling instead, please see what your modifications brought.

![6](https://user-images.githubusercontent.com/77843050/231470128-c6b1d88d-fb4b-4e1a-a376-daa50a9999b4.gif)

2023-04-12 14:12 UTC, AbelG101 approved these changes
![](https://media.giphy.com/media/YPI7uEvEZr7siYRlZD/giphy.gif)

# Hi @Theodoraldo 👋, 

**Your project is complete!  There is nothing else to say other than... it's time to merge it. 
Congratulations! 🎉 🥳🥇**

## Highlights
- Correct use of GitHub Flow ✔
-  Well-structured files ✔
- All linter checks are passing ✔
- Descriptive PR title with a great summary ✔

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-12 14:58 UTC, merged